baseURL = "http://localhost:1313/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Zozo"
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true

pygmentsUseClasses = true
pygmentsCodefences = true


[params]
  gitterRoom = "gitterHQ/sidecar"

[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"